services:
  backend:
    build: 
      context: ./artback
    command: gunicorn artback.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./artback:/artback
      - static_volume:/artback/staticfiles
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./artfront
    ports:
      - "3000:80"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/artback/staticfiles
    depends_on:
      - frontend
      - backend

volumes:
  static_volume: