services:
  backend:
    build: 
      context: ./artback
    volumes:
      - ./artback:/artback
      - static_volume:/artback/staticfiles
      - sqlite_data:/artback/data
    command: gunicorn artback.wsgi --bind 0.0.0.0:8000

  frontend:
    build: 
      context: ./artfront
      target: development
    
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/artback/staticfiles
    depends_on:
      - frontend
      - backend
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}

volumes:
  static_volume:
  sqlite_data: