# docker-compose.prod.yml
services:
  frontend:
    command: npm run preview
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://kichakapoa.com
    build:
      target: production

  backend:
    environment:
      - DJANGO_ENV=production
      - DEBUG=0

  nginx:
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro