# docker-compose.yml

services:
  backend:
    build: 
      context: ./artback
    volumes:
      - ./artback:/artback
      - static_volume:/artback/staticfiles
      - sqlite_data:/artback/data
    expose:
      - "8000"
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-development}
    tty: true
    stdin_open: true

  frontend:
    build: 
      context: ./artfront
      target: builder
      args:
        - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./artfront:/artfront:delegated
      - /artfront/node_modules
    expose:
      - "5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/artback/staticfiles
      - ./artfront/dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
  sqlite_data:
  certbot_data:
  