# docker-compose.yml
services:
  backend:
    build: 
      context: ./artback
    volumes:
      - ./artback:/artback
      - static_volume:/artback/staticfiles
      - sqlite_data:/artback/data
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  frontend:
    build: 
      context: ./artfront
    expose:
      - 8080
    ports:
      - "8080:80"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/artback/staticfiles
      - /etc/letsencrypt/live/kichakapoa.com/fullchain.pem:/etc/letsencrypt/live/kichakapoa.com/fullchain.pem
      - /etc/letsencrypt/live/kichakapoa.com/privkey.pem:/etc/letsencrypt/live/kichakapoa.com/privkey.pem
    depends_on:
      - frontend
      - backend

volumes:
  static_volume:
  sqlite_data: