services:
  backend:
    build: 
      context: ./artback
    volumes:
      - ./artback:/artback
      - static_volume:/artback/staticfiles
      - sqlite_data:/artback/data
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-development}
    tty: true
    stdin_open: true

  frontend:
    build: 
      context: ./artfront
      target: builder
      args:
        - NODE_ENV=${NODE_ENV:-development}
    command: npm run dev
    volumes:
      - ./artfront:/artfront:delegated
      - /artfront/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CHOKIDAR_USEPOLLING=true

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.${ENVIRONMENT:-dev}:/etc/caddy/Caddyfile:ro
      - static_volume:/artback/staticfiles
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}

volumes:
  static_volume:
  sqlite_data:
  caddy_data:
  caddy_config:
  