# Generated by Django 5.1 on 2024-08-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='current_stage',
            field=models.CharField(choices=[('0', 'Ordered'), ('1', 'Splitting/drawing'), ('2', 'Carving/cutting'), ('3', 'Sanding'), ('4', 'Painting'), ('5', 'Finishing'), ('6', 'Packaging'), ('7', 'Done')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('C', 'Completed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='RejectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('0', 'Ordered'), ('1', 'Splitting/drawing'), ('2', 'Carving/cutting'), ('3', 'Sanding'), ('4', 'Painting'), ('5', 'Finishing'), ('6', 'Packaging'), ('7', 'Done')], max_length=1)),
                ('department', models.CharField(choices=[('C', 'Carpentry'), ('P', 'Painting')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('production_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_history', to='production.productiontask')),
            ],
        ),
    ]
