# Generated by Django 5.1 on 2024-08-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productiontask_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rejectionhistory',
            name='department',
            field=models.CharField(blank=True, choices=[('C', 'Carpentry'), ('P', 'Painting')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='rejectionhistory',
            name='production_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_history', to='production.productiontask'),
        ),
        migrations.AlterField(
            model_name='rejectionhistory',
            name='stage',
            field=models.CharField(blank=True, choices=[('0', 'Ordered'), ('1', 'Splitting/drawing'), ('2', 'Carving/cutting'), ('3', 'Sanding'), ('4', 'Painting'), ('5', 'Finishing'), ('6', 'Packaging'), ('7', 'Done')], max_length=1, null=True),
        ),
    ]
