# Generated by Django 5.1 on 2024-08-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_rejectionhistory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='current_stage',
            field=models.CharField(choices=[('0', 'Ordered'), ('1', 'Splitting/drawing'), ('2', 'Carving/cutting'), ('3', 'Sanding'), ('4', 'Painting'), ('5', 'Finishing'), ('6', 'Packaging'), ('7', 'Done')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('C', 'Completed'), ('X', 'Cancelled')], default='I', max_length=1),
        ),
    ]
