# Generated by Django 5.1 on 2024-08-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_staffmember_hire_date_alter_staffmember_role_and_more'),
        ('production', '0004_productiontask_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectionhistory',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_history', to='core.staffmember'),
        ),
        migrations.AlterField(
            model_name='rejectionhistory',
            name='department',
            field=models.CharField(blank=True, choices=[('C', 'Carpentry'), ('S', 'Sanding'), ('P', 'Painting')], max_length=1, null=True),
        ),
    ]
