# Generated by Django 5.1 on 2024-08-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_artist_specialization'),
        ('inventory', '0001_initial'),
        ('production', '0006_rejectionhistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.PositiveIntegerField()),
                ('current_stage', models.CharField(choices=[('0', 'Ordered'), ('1', 'Splitting/drawing'), ('2', 'Carving/cutting'), ('3', 'Sanding'), ('4', 'Painting'), ('5', 'Finishing'), ('6', 'Packaging'), ('7', 'Done')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='authentication.artist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='inventory.item')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
