# Generated by Django 5.1 on 2024-08-19 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='position',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('PROPRIETOR', 'Proprietor'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor')], default='SUPERVISOR', max_length=20),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
