# Generated by Django 5.1 on 2024-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_staffmember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='hire_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('proprietor', 'Proprietor'), ('manager', 'Manager'), ('supervisor', 'Supervisor')], default='supervisor', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
