# Generated by Django 5.1 on 2024-08-24 02:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_artist_specialization'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month', 'artist']},
        ),
        migrations.CreateModel(
            name='AnnualBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('annual_earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_bonuses', to='authentication.artist')),
            ],
            options={
                'ordering': ['-year', 'artist'],
                'unique_together': {('artist', 'year')},
            },
        ),
    ]
