# Generated by Django 5.1 on 2024-09-22 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_options_annualbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
