name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: COPY FILES TO SERVER
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ".,!.git/*,!node_modules"
          target: "~/kichaka"

      - name: BUILD AND DEPLOY
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/kichaka
            echo "ENVIRONMENT=production" > ~/kichaka/.env
            export ENVIRONMENT=production
            make rebuild
            docker compose exec -T backend python manage.py migrate
